title: BSides Kraków
description: > # this means to ignore newlines until "baseurl:"
  Security BSides Kraków
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bsideskrakow.pl" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Facebook Page
  link: "https://www.facebook.com/bsideskrakow"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/bsideskrakow
  - title: twitter
    url: https://twitter.com/bsideskrakow

# Build settings
markdown: kramdown
permalink: pretty